<?php

/**
 * @file
 * Contains hooks for paragraphs_paste module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\paragraphs_paste\Form\ParagraphsPasteForm;


/**
 * Implements hook_field_widget_multivalue_form_alter().
 */
function paragraphs_paste_field_widget_multivalue_paragraphs_form_alter(array &$elements, FormStateInterface $form_state, array $context) {
  \Drupal::service('class_resolver')
    ->getInstanceFromDefinition(ParagraphsPasteForm::class)
    ->formAlter($elements, $form_state, $context);
}
