name: Check coding styles

on: [pull_request]

jobs:
  phpcs:
    name: runner / phpcs
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1

      - name: phpcs
        uses: chrfritsch/action-drupal-coder@v1
        with:
          github_token: ${{ secrets.github_token }}
          level: error
          filter_mode: nofilter
